image: liuyangzhuan/superlu_gpu_amd64:v1.2
tags: 
  # - hpsf
  - x86_64-nvidiagpu

stages:
  - build
  - test

build:
  stage: build

  script:
    - cd ~/superlu_dist

  artifacts:
    paths:
      - build
    expire_in: 1 week

test 1/4:
  stage: test
  script:
    - export TEST_NUMBER=1
    - sh runit.sh

test 2/4:
  stage: test
  script:
    - export TEST_NUMBER=2
    - sh runit.sh

test 3/4:
  stage: test
  script:
    - export TEST_NUMBER=3
    - sh runit.sh

test 4/4:
  stage: test
  script:
    - export TEST_NUMBER=4
    - sh runit.sh
