image: liuyangzhuan/superlu_gpu_amd64:v1.2

stages: [build, test]

default:
  tags: [hpsf-gpu, x86_64-nvidiagpu, nvidia-h100]


build:
  stage: build
  script:
    - cd ~/superlu_dist/superlu_dist
    - git pull
    - cd build
    - make install -j
    - cd ../../
    - cp -r superlu_dist $CI_PROJECT_DIR/build_artifact

  artifacts:
    paths:
      - build_artifact
    expire_in: 1 week

test 1/4:
  stage: test
  needs: [build]
  script:
    - cd ~/superlu_dist/superlu_dist/
    - cp -r $CI_PROJECT_DIR/build_artifact/* . 
    - export TEST_NUMBER=1
    - ls -altr 
    - ./.ci_tests_gpu.sh


