stages:
  - build

# -------------------------
# Debug job to inspect hpsf image
# -------------------------
debug:hpsf:
  stage: build
  tags: 
    - hpsf
  script:
    - echo "=== OS Info ==="
    - cat /etc/os-release
    - uname -a
    - module list
    - module load e4s
    - module load cuda
    - module load cmake 
# # -------------------------
# # Include gh-gl-sync component for mirroring
# # -------------------------
# include:
#   - component: $CI_SERVER_FQDN/dav-sdk/gh-gl-sync/github-sync@~latest
#     inputs:
#       github_project: liuyangzhuan/hpsf-debug-mirror
#       gitlab_repo: git@ssh.gitlab.spack.io:SSG/hpsf-debug-mirror-target.git
#       gitlab_host: https://gitlab.spack.io/
#       gitlab_project: SSG/hpsf-debug-mirror-target
#       prereq_check: format
#       status_context: "Debug CI"
#       sync_draft_prs: true
#     rules:
#       - if: $CI_SERVER_HOST == "gitlab.spack.io"